account/urls.py
from django.urls import path
from .views import login,register,contact_register,logout
app_name = 'registration'
urlpatterns = [
	path('contact_register/',contact_register,name='contact_register'),
	path('login/',login,name='login'),
	path('logout/',logout,name='logout'),
	path('register/',register,name='register'),
]

online_class/urls.py
from django.urls import path
from .views import (
	index,about,blog_single,
	blog,contact,course_single,courses,
	subjects,first_subjects,
	second_subjects,third_subjects,fourth_subjects,fifth_subjects,sixth_subjects,seventh_subjects)
app_name = 'online_class'
urlpatterns = [
	path('',index,name='index'),
	path('index/',index,name='index'),
	path('about/',about,name='about'),
	path('blog-single/',blog_single,name='blog_single'),
	path('blog/',blog,name='blog'),
	path('contact/',contact,name='contact'),
	path('course-single/',course_single,name='course_single'),
	path('courses/',courses,name='courses'),
	path('subjects/',subjects,name='subjects'),
	path('subjects1/',first_subjects,name='first_subjects'),
	path('subjects2/',second_subjects,name='second_subjects'),
	path('subjects3/',third_subjects,name='third_subjects'),
	path('subjects4/',fourth_subjects,name='fourth_subjects'),
	path('subjects5/',fifth_subjects,name='fifth_subjects'),
	path('subjects6/',sixth_subjects,name='sixth_subjects'),
	path('subjects7/',seventh_subjects,name='seventh_subjects'),

]

online_learning/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('',include('online_class.urls')),
    path('accounts/',include('account.urls')),
    path('admin/', admin.site.urls),
]

account/models.py
from django.db import models

# Create your models here.
class UserContactModel(models.Model):
	name = models.CharField(max_length=200)
	phone = models.IntegerField()
	email = models.EmailField(max_length=100)
	description = models.TextField()

online_class/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from .models import UserContactModel
# Create your views here.
def contact_register(request):
	if request.method == 'POST':
		name = request.POST['name']
		phone = request.POST['phone']
		email = request.POST['email']
		description = request.POST['description']
		user_contact = UserContactModel.objects.create(name=name,phone=phone,email=email,description=description)
		user_contact.save()
		return redirect('/')
	else:
		return render(request,'contact.html')		
def register(request):
	if request.method == 'POST':
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		username = request.POST['username']
		password1 = request.POST['password1']
		password2 = request.POST['password2']
		email = request.POST['email']
		if User.objects.filter(username=username).exists():
			messages.info(request,'Username already exists')
			return redirect('registration:register')
		elif User.objects.filter(email=email).exists():
			messages.info(request,'email already exists')
			return redirect('registration:register')
		else:
			user=User.objects.create_user(first_name=first_name,last_name=last_name,username=username,password=password2,email=email)
			user.save()
			return redirect('registration:login')
		return redirect('registration:register')
	else:
		return render(request,'register.html')	
def login(request):
	if request.method == 'POST':
		username = request.POST.get('username',False);
		password = request.POST.get('password',False);
		user = auth.authenticate(username=username,password=password)
		if user is not None:
			auth.login(request,user)
			return redirect('/')
		else:
			messages.info(request,'Invalid credintial')	
			return redirect('registration:login')	
	else:
		 return render(request,'login.html')
def logout(request):
	auth.logout(request)
	return redirect('/')

online_class/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request,'index.html')
def about(request):
	return render(request,'about.html')	
def blog_single(request):
	return render(request,'blog-single.html')
def blog(request):
	return render(request,'blog.html')
def contact(request):
	return render(request,'contact.html')		
def course_single(request):
	return render(request,'course-single.html')
def courses(request):
	return render(request,'courses.html')	
def subjects(request):
	return render(request,'subjects.html')	
def first_subjects(request):
	return render(request,'subjects1.html')
def second_subjects(request):
	return render(request,'subjects2.html')			
def third_subjects(request):
	return render(request,'subjects3.html')
def fourth_subjects(request):
	return render(request,'subjects4.html')
def fifth_subjects(request):
	return render(request,'subjects5.html')
def sixth_subjects(request):
	return render(request,'subjects6.html')
def seventh_subjects(request):
	return render(request,'subjects7.html')	

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>TFR Education </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,900" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

  <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

  <!-- Theme Style -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!--style for Blog.html-->
  <style>

.dropdown-submenu {
        position: relative;
    }

    .dropdown-submenu>.dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
        margin-left: 0;
        border-radius: 0.25rem;
    }

    .dropdown-submenu1>.dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
        margin-left: 0;
        border-radius: 0.25rem;
    }
/*
    .dropdown-submenu:hover>.dropdown-menu {
        display: block;
    }
    */
/*
    .dropdown-submenu>a::after {
        border-bottom: 0.3em solid transparent;
        border-left-color: inherit;
        border-left-style: solid;
        border-left-width: 0.3em;
        border-top: 0.3em solid transparent;
        content: " ";
        display: block;
        float: right;
        height: 0;
        margin-right: -0.6em;
        margin-top: -0.95em;
        width: 0;
    }
    */
/*
    .dropdown-submenu.pull-left {
        float: none;
    }
*/
    .dropdown-submenu.pull-left>.dropdown-menu {
        left: -75%;
    }
/*
    .dropdown-menu .divider {
        background-color: #e5e5e5;
        height: 1px;
        margin: 9px 0;
        overflow: hidden;
    }
    */
  </style>
</head>

<body>
  {% include 'nav.html' %}
  {% block content %}
   replace me
  {% endblock %}
  {% include 'footer.html' %}
  <!-- loader -->
  <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#f4b214" /></svg></div>

  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>


  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="site-hero site-hero-innerpage overlay" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/work1.jpg' %});">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
              <h1>Contact Us</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

<!--Scroll top button-->
  <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <script>
    //Get the button
    var mybutton = document.getElementById("myBtn");
    
    // When the user scrolls down 20px from the top of the document, show the button
    window.onscroll = function() {scrollFunction()};
    
    function scrollFunction() {
      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        mybutton.style.display = "block";
      } else {
        mybutton.style.display = "none";
      }
    }
    
    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
      document.body.scrollTop = 0;
      document.documentElement.scrollTop = 0;
    }
    </script>
  <!--Scroll end of code-->

    <section class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <form action="{% url 'registration:contact_register'%}" method="POST">{% csrf_token %}
                  <div class="row">
                    <div class="col-md-4 form-group">
                      <label for="name">Name</label>
                      <input type="text" name='name' id="name" class="form-control ">
                    </div>
                    <div class="col-md-4 form-group">
                      <label for="phone">Phone</label>
                      <input type="text" name='phone' id="phone" class="form-control ">
                    </div>
                    <div class="col-md-4 form-group">
                      <label for="email">Email</label>
                      <input type="email" name="email" id="email" class="form-control ">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 form-group">
                      <label for="message">Write Message</label>
                      <textarea name="description" id="message" class="form-control " cols="30" rows="8"></textarea>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input type="submit" value="Send Message" class="btn btn-primary">
                    </div>
                  </div>
                </form>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

     <section class="overflow">
      <div class="container">
        <div class="row justify-content-center align-items-center">
          
          
          <div class="col-lg-7 order-lg-3 order-1 mb-lg-0 mb-5">
            <img src="{% static 'images/anish cafe re .png' %}" alt="Image placeholder" class="img-md-fluid">
          </div>
          <div class="col-lg-1 order-lg-2"></div>
          <div class="col-lg-4 order-lg-1 order-2 mb-lg-0 mb-5">
            <blockquote class="testimonial">
              &ldquo; Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt incidunt nihil ab cumque molestiae commodi. &rdquo;
            </blockquote>
            <p>&mdash; Anish Mandal, Certified JS Student</p>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    
{% endblock %}

templates/courses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url({% static 'images/big_image_1.jpg' %});">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
              <h1>Level Up Your Skills</h1>
              <p class="lead">See our courses Below. Learn something new every day with skwela lorem ipsum dolor sit amet.</p>
              <p><a href="#" class="btn btn-primary">Sign up and get a 7-day free trial</a></p>
            </div>

            
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->


    <section class="site-section bg-light">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center">
            <h2>Our Courses</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum magnam illum maiores adipisci pariatur, eveniet.</p>
          </div>
        </div>
        <div class="row top-course">
          <div class="col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/webdesign.jpg' %}" alt="Image placeholder">
              <h2>Web Design 101</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/wordpress.jpg' %}" alt="Image placeholder">
              <h2>Learn How To Develop WordPress Plugin</h2>
              <p>Enroll Now</p>
            </a>
          </div>

          <div class="col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/javascript.jpg' %}" alt="Image placeholder">
              <h2>JavaScript 101</h2>
              <p>Enroll Now</p>
            </a>
          </div>

        </div>

        <!-- END row -->

        <div class="row top-course">
          <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/webdesign.jpg' %}" alt="Image placeholder">
              <h2>Web Design 101</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/wordpress.jpg' %}" alt="Image placeholder">
              <h2>Learn How To Develop WordPress Plugin</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/javascript.jpg' %}" alt="Image placeholder">
              <h2>JavaScript 101</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/photoshop.jpg' %}" alt="Image placeholder">
              <h2>Photoshop Design 101</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/reactjs.jpg' %}" alt="Image placeholder">
              <h2>Learn Native ReactJS</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/angularjs.jpg' %}" alt="Image placeholder">
              <h2>Learn AngularJS 2</h2>
              <p>Enroll Now</p>
            </a>
          </div>
        </div>
        <!-- END row -->

        
        <div class="row top-course">
          <div class="col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/photoshop.jpg' %}" alt="Image placeholder">
              <h2>Photoshop Design 101</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/reactjs.jpg' %}" alt="Image placeholder">
              <h2>Learn Native ReactJS</h2>
              <p>Enroll Now</p>
            </a>
          </div>
          <div class="col-md-4 col-sm-6 col-12">
            <a href="{% url 'online_class:course_single' %}" class="course">
              <img src="{% static 'images/angularjs.jpg' %}" alt="Image placeholder">
              <h2>Learn AngularJS 2</h2>
              <p>Enroll Now</p>
            </a>
          </div>
        </div>
        <!-- END row -->
      </div>
    </section>
    <!-- END section -->

    <section class="site-section">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center">
            <h2>Meet Your Instructors</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum magnam illum maiores adipisci pariatur, eveniet.</p>
          </div>
        </div>
        <section class="school-features text-dark d-flex">

          <div class="inner">
            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Rhea Smith</h3>
                <p class="instructor-meta">WordPress Expert</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora fuga suscipit numquam esse saepe quam, eveniet iure assumenda dignissimos aliquam!</p>
              </div>
            </div>

            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_2.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Gregg White</h3>
                <p class="instructor-meta">HTML4, CSS3 Expert</p>
                <p>Delectus fuga voluptatum minus amet, mollitia distinctio assumenda voluptate quas repellat eius quisquam odio. Aliquam, laudantium, optio? Error velit, alias.</p>
              </div>
            </div>

            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_3.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Rob Gold</h3>
                <p class="instructor-meta">JS Expert</p>
                <p>Delectus fuga voluptatum minus amet, mollitia distinctio assumenda voluptate quas repellat eius quisquam odio. Aliquam, laudantium, optio? Error velit, alias.</p>
              </div>
            </div>


            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Wennie Poe</h3>
                <p class="instructor-meta">Angular JS Expert</p>
                <p>Harum, adipisci, aspernatur. Vero repudiandae quos ab debitis, fugiat culpa obcaecati, voluptatibus ad distinctio cum soluta fugit sed animi eaque?</p>
              </div>
            </div>
          </div>
        </section>

        <section class="school-features text-dark last d-flex">

          <div class="inner">
            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Rhea Smith</h3>
                <p class="instructor-meta">WordPress Expert</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora fuga suscipit numquam esse saepe quam, eveniet iure assumenda dignissimos aliquam!</p>
              </div>
            </div>

            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_2.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Gregg White</h3>
                <p class="instructor-meta">Photoshop Expert</p>
                <p>Delectus fuga voluptatum minus amet, mollitia distinctio assumenda voluptate quas repellat eius quisquam odio. Aliquam, laudantium, optio? Error velit, alias.</p>
              </div>
            </div>

            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_3.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Rob Gold</h3>
                <p class="instructor-meta">Web Design Expert</p>
                <p>Delectus fuga voluptatum minus amet, mollitia distinctio assumenda voluptate quas repellat eius quisquam odio. Aliquam, laudantium, optio? Error velit, alias.</p>
              </div>
            </div>


            <div class="media d-block feature text-center">
              <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder" class="mb-3">
              <div class="media-body">
                <h3 class="mt-0">Wennie Poe</h3>
                <p class="instructor-meta">React JS Expert</p>
                <p>Harum, adipisci, aspernatur. Vero repudiandae quos ab debitis, fugiat culpa obcaecati, voluptatibus ad distinctio cum soluta fugit sed animi eaque?</p>
              </div>
            </div>
          </div>
        </section>


      </div>
    </section>
    <!-- END section -->

    <section class="section-cover bg-dark">
      <div class="container">
        <div class="row justify-content-center align-items-center intro">
          <div class="col-md-7 text-center element-animate">
            <h2>Sign Up And Get a 7-day Free Trial</h2>
            <p class="lead mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto quidem tempore expedita facere facilis, dolores!</p>
            <p><a href="#" class="btn btn-primary">Sign up and get a 7-day free trial</a></p>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->


    <!--Scroll top button-->
  <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <script>
    //Get the button
    var mybutton = document.getElementById("myBtn");
    
    // When the user scrolls down 20px from the top of the document, show the button
    window.onscroll = function() {scrollFunction()};
    
    function scrollFunction() {
      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        mybutton.style.display = "block";
      } else {
        mybutton.style.display = "none";
      }
    }
    
    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
      document.body.scrollTop = 0;
      document.documentElement.scrollTop = 0;
    }
    </script>
  <!--Scroll end of code-->
{% endblock %}

templates/footer.html
 {% load static %}
  <footer class="site-footer" style="background-image: url({% static 'images/img_bg_4.jpg' %});">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-4">
          <h3>About</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi, accusantium optio unde perferendis eum
            illum voluptatibus dolore tempora, consequatur minus asperiores temporibus reprehenderit.</p>
        </div>
        <div class="col-md-6 ml-auto">
          <div class="row">
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Company</a></li>
                <li><a href="#">Teachers</a></li>
                <li><a href="#">Courses</a></li>
                <li><a href="#">Categories</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Company</a></li>
                <li><a href="#">Teachers</a></li>
                <li><a href="#">Courses</a></li>
                <li><a href="#">Categories</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">+977 9862170694</a></li>
                <li><a href="#">mandalktaanees12@gmail.com</a></li>
                <li><a href="#">+977 9815364509</a></li>
                <li><a href="#">+977 9804782268</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p>
            
            Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> All rights reserved to <a href="www.google.com" target="_blank">TFR</a>
           
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- END footer -->

templates/nav.html
 {% load static %}
  <header role="banner">
    <nav class="navbar navbar-expand-md navbar-dark bg-light">
      <div class="container">
        <a class="navbar-brand absolute" href="{% url 'online_class:index' %}">TFR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
          aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'online_class:index' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'online_class:courses' %}" id="dropdown04" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">B.E Computer</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                
                <a class="dropdown-item" href="{% url 'online_class:subjects' %}">Semester I</a>
                <a class="dropdown-item" href="{% url 'online_class:first_subjects' %}">Semester II</a>
                <a class="dropdown-item" href="{% url 'online_class:second_subjects' %}">Semester III</a>
                <a class="dropdown-item" href="{% url 'online_class:third_subjects' %}">Semester IV</a>
                <a class="dropdown-item" href="{% url 'online_class:fourth_subjects' %}">Semester V</a>
                <a class="dropdown-item" href="{% url 'online_class:fifth_subjects' %}">Semester VI</a>
                <a class="dropdown-item" href="{% url 'online_class:sixth_subjects' %}">Semester VII</a>
                <a class="dropdown-item" href="{% url 'online_class:seventh_subjects' %}">Semester VIII</a>
              </div>

            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">Categories</a>
              <div class="dropdown-menu" aria-labelledby="dropdown05">
                <a class="dropdown-item" href="#">Software Programming</a>
                <a class="dropdown-item" href="#">Hardware and Networking</a>
                <a class="dropdown-item" href="#">Graphic Design</a>
                <a class="dropdown-item" href="#">online_class Clases</a>
                <a class="dropdown-item" href="#">Web Development</a>
              </div>

            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'online_class:blog' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'online_class:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'online_class:contact' %}">Contact</a>
            </li>
          </ul>

          <ul class="navbar-nav absolute-right">
            {% if user.is_authenticated and not user.is_superuser %}
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{% static 'images/face.png' %}" class="profile-image img-circle"> {{user.first_name}}</ <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li><a href="#"><i class="fa fa-cog"></i> Account</a></li>
                      <li class="divider"></li>
                      <li><a href="{% url 'registration:logout' %}"><i class="fa fa-cog"></i> Sign-out</a></li>
                  </ul>
              </li>             
            {% else %}
              <li class="nav-item">
                <a href="{% url 'registration:login' %}" class="nav-link">Login</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'registration:register' %}" class="nav-link">Register</a>
              </li>
             <li class="nav-item">
                <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
              </li>
              {% endif %}
          </ul>

        </div>
      </div>
    </nav>
  </header>
  <!-- END header -->